### ISSUE TITLE
有使用网络验证实现的项目

### ISSUE THREAD

**Issue by yinghope** [qdddz/HFUT_AutoSubmit#1]
这个[https://github.com/HowardZorn/hfut_auto_check-in](url)
全部使用网络验证实现。
当然你这个也是很方便使用的，是完成这种自动化任务的新思路，反正都是本菜鸡赶不上的高度。。

**Comment by qdddz** [comment]
打算去和作者py，完成二合一

**Comment by yinghope** [comment]
强烈支持
