### ISSUE TITLE
关于3.27日更新后的打卡问题

### ISSUE THREAD

**Issue by liujilong0116** [qdddz/HFUT_AutoSubmit#11]
运行最新上传的代码后，log显示结果为已打卡，实际上未打卡成功，请问这个问题可以解决么？

**Comment by qdddz** [comment]
有bug，因为加入了是否打卡的检测，检测逻辑目前还有问题

**Comment by forchannot** [comment]
感谢大佬，希望大佬早日修复，不过也要注意自己的保护，上一个为hfutgo提供自动打卡的研究生学长已经被学校发现处罚了

**Comment by liujilong0116** [comment]
if last_form['data']['TBSJ'] == "%04d-%02d-%02d" % today:
       return 2
这两句注释掉还是没法打上卡耶。     现在最新上传的代码是ok的么大佬

**Comment by forchannot** [comment]
> 有bug，因为加入了是否打卡的检测，检测逻辑目前还有问题

大佬，sever酱发来两次通知，一次成功一次失败

**Comment by qdddz** [comment]
现在应该是修完了

**Comment by imzoet** [comment]
测试了一下，输出打卡失败

**Comment by qdddz** [comment]
这次是真好了，昨天发现逻辑今天又变动了。。。重新fork就行

**Comment by imzoet** [comment]
成功了，感谢大佬！

**Comment by forchannot** [comment]
> 这次是真好了，昨天发现逻辑今天又变动了。。。重新fork就行

![image](https://user-images.githubusercontent.com/100580891/160360478-948c12da-d98a-4e6e-960d-a01c1bcbb5f2.png)
这个问题怎么解决呢
