### ISSUE TITLE
网络超时问题

### ISSUE THREAD

**Issue by qdddz** [qdddz/HFUT_AutoSubmit#12]
![image](https://user-images.githubusercontent.com/100580891/160360478-948c12da-d98a-4e6e-960d-a01c1bcbb5f2.png)
这个问题怎么解决呢，我就把那个sckey改成了新版了，把旧版的注释掉了
![image](https://user-images.githubusercontent.com/100580891/160361445-6e29abfb-eef4-4633-93fe-b0f2f5f316ae.png)
就把这里注释了下

_Originally posted by @forchannot in https://github.com/qdddz/HFUT_AutoSubmit/issues/11#issuecomment-1080363608_

**Comment by qdddz** [comment]
这种问题是因为我们学校的网垃圾
![image](https://user-images.githubusercontent.com/25915356/160365021-3ff539a5-6098-4f64-aba6-07c7c6465b4a.png)

**Comment by forchannot** [comment]
> 这种问题是因为我们学校的网垃圾 ![image](https://user-images.githubusercontent.com/25915356/160365021-3ff539a5-6098-4f64-aba6-07c7c6465b4a.png)

![image](https://user-images.githubusercontent.com/100580891/160387470-0a815587-64a3-4193-9228-9f9e927892fe.png)
这些全都是网络超时吗（笑哭），我的账号密码应该没填错，等明天看看能不能成功

**Comment by imzoet** [comment]
建议用本地IDE试试，或者搬运到腾讯云上

**Comment by forchannot** [comment]
> 建议用本地IDE试试，或者搬运到腾讯云上

小白不是特别会，要怎么改main函数才能让他在腾讯云上面跑呢

**Comment by imzoet** [comment]
可以看看官方的文档，腾讯云会比较麻烦，还得添加依赖之类的，还是建议你用本地IDE，实在不行，就把GitHub workflow设置成一天多跑几次保证稳定

**Comment by forchannot** [comment]
> 可以看看官方的文档，腾讯云会比较麻烦，还得添加依赖之类的，还是建议你用本地IDE，实在不行，就把GitHub workflow设置成一天多跑几次保证稳定

今天跑成功了，稳定性就不知道了，感谢大佬
