### ISSUE TITLE
能否脚本运行成功但打卡失败后继续尝试打卡

### ISSUE THREAD

**Issue by forchannot** [qdddz/HFUT_AutoSubmit#15]
如题，现在的代码是当日打卡失败但是脚本运行成功后，后续运行脚本会提示今日已打卡。能否加个检测打卡失败后重新打卡，直到成功为止或者超出规定时间

**Comment by qdddz** [comment]
代码逻辑里是有的，但是今天应该是系统改了打卡逻辑

**Comment by forchannot** [comment]
> 代码逻辑里是有的，但是今天应该是系统改了打卡逻辑

好的，等大佬适配下新的打卡逻辑
