### ISSUE TITLE
这个怎么解决

### ISSUE THREAD

**Issue by forchannot** [qdddz/HFUT_AutoSubmit#21]
![image](https://user-images.githubusercontent.com/100580891/168020030-7f14cf93-bec4-4e7a-8738-13890d46b9cd.png)
![image](https://user-images.githubusercontent.com/100580891/168020563-15f3ba52-5b63-4e0d-9cc3-a1dbd131fc5d.png)

**Comment by qdddz** [comment]
![图片1](https://user-images.githubusercontent.com/25915356/168022233-4bc9abbd-f4f0-4e8d-9a95-0eaa11b7349b.png)
我的，这两行忘记加了

**Comment by forchannot** [comment]
> ![图片1](https://user-images.githubusercontent.com/25915356/168022233-4bc9abbd-f4f0-4e8d-9a95-0eaa11b7349b.png) 我的，这两行忘记加了

新增的这个force怎么填写呢

**Comment by qdddz** [comment]
不用填写，我自己调试用的，对代码没有影响



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qdddz/HFUT_AutoSubmit] 这个怎么解决 (Issue #21)





  
 我的，这两行忘记加了
  
新增的这个force怎么填写呢
