### ISSUE TITLE
能否增加失败重试呢

### ISSUE THREAD

**Issue by andcarefree** [qdddz/HFUT_AutoSubmit#3]
好像是因为学校网络的原因，这脚本时灵时不灵的。请问可以说是增加重试逻辑吗，就发生网络连接超时这一类错误的时候过半小时重试？

**Comment by qdddz** [comment]
可以拆分成两个job
第一个从两点开始每隔三十分钟试一次直到五点
第二个在五点时检测是否成功

**Comment by andcarefree** [comment]
> 可以拆分成两个job
> 第一个从两点开始每隔三十分钟试一次直到五点
> 第二个在五点时检测是否成功

谢谢大佬造福工大学子嗷🐮
