### ISSUE TITLE
建议上阿里云自动化打卡

### ISSUE THREAD

**Issue by xzz024** [qdddz/HFUT_AutoSubmit#9]
感谢大佬的研究！
建议从GitHub上改为阿里云或腾讯云的云函数上定时运行。国内的云服务可以精确到秒级打卡而且特别稳定一次就可以。
![image](https://user-images.githubusercontent.com/68104786/158946924-630befd9-e69d-4f25-8dcd-027cf070b365.png)

**Comment by qdddz** [comment]
我这个纯纯为了服务小白，有需要可以自己改的
